init_deploy:
  input_size: [3, 28]
  patch_size: 1
  in_channels: 3
  hidden_size: 16
  depth: 6
  num_heads: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  num_classes: 1
  learn_sigma: True

track_generator:

  input_size: [12, 140]
  patch_size: 1
  in_channels: 3
  hidden_size: 32
  depth: 6
  num_heads: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  num_classes: 2
  learn_sigma: True


train:
  init_deploy_path: './datasets/init_dataset1.pth'
  track_data_path: './datasets/Track_dataset_smooth.pth'
  lr: 1e-4
  batch_size: 32
  num_epoch: 5000
  log_per_steps: 500
  save_checkpoint_per_steps: 10000

sample:
  init_deploy_path: "./results/2025-03-02_19-53-13/model/0200000.pt"
  track_generator_path: "./results/2024-10-22_20-13-26/model/0140000.pt"
  seed: 456
  num_sampling_steps: 1000
  num_samples: 8000
  scale: 4


diffusion:
  timestep_respacing: ''
  noise_schedule: "linear" 
  use_kl: False
  sigma_small: False
  predict_xstart: False
  learn_sigma: True
  rescale_learned_sigmas: False
  diffusion_steps: 1000
