init_deploy:
  input_size: [3, 28]
  patch_size: 1
  in_channels: 1
  hidden_size: 16
  depth: 6
  num_heads: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  num_classes: 2
  learn_sigma: True

track_generator:

  input_size: 140
  in_channels: 36
  hidden_size: 128
  depth: 6
  num_heads: 4
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  num_classes: 2
  learn_sigma: True


train:
  init_deploy_path: './datasets/init_dataset.pth'
  track_data_path: './datasets/Track_dataset_smooth.pth'
  lr: 1e-4
  batch_size: 32
  num_epoch: 2500
  log_per_steps: 500
  save_checkpoint_per_steps: 10000

sample:
  init_deploy_path: "./results/2024-10-03_11-39-14/model/1750000.pt"
  track_generator_path: "./results/2025-02-27_19-28-33/model/2900000.pt"
  seed: 123
  num_sampling_steps: 1000
  num_samples: 8000
  scale: 1


diffusion:
  timestep_respacing: ''
  noise_schedule: "linear" 
  use_kl: False
  sigma_small: False
  predict_xstart: False
  learn_sigma: True
  rescale_learned_sigmas: False
  diffusion_steps: 1000
